apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: ankitdhebarin/nginx_ankit:v1-release
      ports:
        - containerPort: 80
