apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-lb
  labels:
    app: usermgmt-restapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  type: LoadBalancer #Classic LoadBalancer is the default choice
  selector:
    app: usermgmt-restapp
  ports:
    - name: http
      port: 80
      targetPort: 8095 # Container port


