apiVersion: v1
kind: Service
metadata:
  name: my-backend-service #Important part
  labels:
    app: backend-restapp
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend-restapp
  ports:
    - name: http
      port: 8080 # Clusterip service port
      targetPort: 8080 # Container port