apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service #Important part
  labels:
    app: frontend-nginx
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-nginx
  ports:
    - name: http
      port: 80 
      targetPort: 80 # Container port
      nodePort: 31234


