apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp1-rs
  labels:
    app: myapp1-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: myapp1-pod
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp1-container
          image: ankitdhebarin/nginx_ankit:v2
          ports:
            - containerPort: 80
        