apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-services
spec:
  type: NodePort
  selector:
    app: myapp1
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31232

